### ISSUE TITLE
Add support for AMQP.Connection.Open options

### ISSUE THREAD

**Issue by joecorkerton** [meltwater/gen_rmq#141]
`AMQP.Connection.Open` allows you to specify options along with a URI https://hexdocs.pm/amqp/AMQP.Connection.html#open/2

We would like to enable ssl via linking to a local cacert, which is not currently possible using a URI.

It would be great if inside init it was possible to add a list of options that get passed to `Connection.open`

**Comment by Shemeikka** [comment]
Hi,

I actually had this same problem and I was just about to open a new issue when I found this one.

I found a simple solution to this problem. It's a small hack but it should work. Currently you can only specify one parameter ('uri') that is passed to the Connection during init but the code actually also accepts Connection's options. Meaning that you can just pass your connection options as uri.

Example:
`uri: [host: "rabbitmq", username: "foo", password: "bar", ssl_options: [xxx]]`

Better solution would be to add a new argument called 'connection' to the init and deprecate the 'uri' argument.

**Comment by mkorszun** [comment]
@Shemeikka regarding connection parameter, is this https://github.com/meltwater/gen_rmq/issues/36 what you are thinking of?

**Comment by Shemeikka** [comment]
@mkorszun I don't think it's what I'm after. If I understood right, that issue is about passing an existing AMQP connection to consumer.

My thought is just to add a new argument 'connection' and use it like the current 'uri'. It would be better understood since 'uri' argument already works like 'connection' argument but the name implies it can only contain few of the connection options and not all of them.

**Comment by mkorszun** [comment]
Fixed with https://github.com/meltwater/gen_rmq/pull/149
