### ISSUE TITLE
Let publisher declare queue within init/0

### ISSUE THREAD

**Issue by cstaud** [meltwater/gen_rmq#66]
To declare a queue is only possible for the consumer. But the producer should also be able to declare the queue before pushing messages to avoid message loss in case no consumer created the queue previously. I am pretty new to rabbitmq and its implementation best practices, but as I understood Producer and Consumer should care for creating relevant queues before publishing or consuming. 
Please give advice in case I'm wrong.

**Comment by mkorszun** [comment]
Thanks for reaching out. 

In general I can see your point, but the biggest issue is that re-declaring the queue with different arguments (ttl, priority, etc.) can break either consumer or publisher (depends on startup order). 

So, you would need to ensure that publisher / consumer queue config is always in sync - this might be hard and error prone.

Another disadvantage of the queue declaration in publisher, is fact that there might multiple queues bound to given exchange. This would get even more complicated, since your publisher would need to know all of them.

**Comment by cstaud** [comment]
Thanks for your insights. Your points look valid to me. 
But isn't it worse if you miss messages without notice instead of raising an error on startup?!

In my special case the elixir app acts only as producer. Do you have experience to work around such issues?

Thanks in advance!

**Comment by mkorszun** [comment]
Hi,

I see couple of options:
* We could extend publisher implementation, to accept optional queue name to bind to provided exchange. Of course we would need to make number of assumptions regarding queue attributes.
* Introduce some kind of utils module, which will provide basic amqp functionality, so we could use it explicitly in a publisher:
~~~
defmodule ExamplePublisher do
  @behaviour GenRMQ.Publisher

  def start_and_bind(opts) do
    GenRMQ.Utils.create_queue(opts)
    GenRMQ.Publisher.start_link(__MODULE__, name: __MODULE__)
  end

  def publish_message(message, routing_key) do
    GenRMQ.Publisher.publish(__MODULE__, message, routing_key)
  end

  def init() do
    [
      exchange: "example_exchange",
      uri: "amqp://guest:guest@localhost:5672"
    ]
  end
end
~~~
* Start consumer, to ensure that queue is created and bound. Define specific routing key for a consumer, which will prevent messages from being consumed.

**Comment by vorce** [comment]
I will close this now, I hope the proposed options by @mkorszun are good enough.
